In [1]:
%autosave 500

Autosaving every 500 seconds


In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import random as rand
from numpy import array
import itertools
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import zero_one_loss, log_loss
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Open a Dataset

In [4]:
def openDataset(filename):
    dataFile = open(filename, 'r')
    dataFrame = pd.read_csv(dataFile, sep=',', header=0)
    dataFile.close()

    return dataFrame

In [6]:
breast = openDataset('breast-cancer.csv')
breast[' deg-malig'] = breast[' deg-malig'].astype(str)
breast_df_original_one_hot = pd.get_dummies(breast)

In [7]:
#Decide how much '?' randomly put in the currently row & put it in a random column position; do it for every sample

In [8]:
maxMissingValues = rand.randint (0, 3)

def randomicAssignment ():
    for i in range(0, len(breast)):
        for j in range(0, maxMissingValues):
            missingValues = rand.randint (0, len(breast.columns) - 1)
            breast.iloc[i, missingValues] = '?'
    
    return breast

In [9]:
newBreast = randomicAssignment()
newBreast

class    age  menopause  tumor-size  inv-nodes  node-caps  \
0                       ?  30-39    premeno           ?        0-2         no   
1    no-recurrence-events  40-49          ?           ?        0-2         no   
2    no-recurrence-events  40-49    premeno       20-24          ?          ?   
3                       ?      ?       ge40       15-19        0-2         no   
4    no-recurrence-events  40-49    premeno         0-4        0-2          ?   
5    no-recurrence-events  60-69       ge40       15-19        0-2          ?   
6                       ?  50-59    premeno       25-29        0-2         no   
7    no-recurrence-events  60-69       ge40           ?        0-2         no   
8                       ?  40-49    premeno       50-54          ?         no   
9    no-recurrence-events  40-49    premeno           ?          ?         no   
10                      ?  40-49    premeno         0-4        0-2         no   
11   no-recurrence-events  50-59       ge40       25-29          ?         no   
12   no-recurrence-events  60-69       lt40       10-14          ?          ?   
13   no-recurrence-events  50-59          ?       25-29        0-2         no   
14   no-recurrence-events  40-49    premeno       30-34          ?         no   
15   no-recurrence-events  60-69       lt40       30-34          ?         no   
16                      ?  40-49    premeno       15-19          ?         no   
17   no-recurrence-events  50-59    premeno       30-34          ?          ?   
18   no-recurrence-events      ?       ge40       30-34        0-2         no   
19                      ?  50-59       ge40       30-34        0-2          ?   
20   no-recurrence-events  50-59          ?       40-44          ?         no   
21   no-recurrence-events      ?          ?       15-19          ?         no   
22   no-recurrence-events  30-39          ?           ?        0-2         no   
23   no-recurrence-events  50-59          ?       40-44        0-2         no   
24   no-recurrence-events  50-59    premeno       35-39          ?          ?   
25   no-recurrence-events  40-49    premeno       25-29        0-2         no   
26   no-recurrence-events  50-59    premeno           ?        0-2         no   
27   no-recurrence-events  60-69       ge40       25-29        0-2         no   
28                      ?      ?    premeno       40-44        0-2         no   
29   no-recurrence-events      ?          ?       30-34        0-2         no   
..                    ...    ...        ...         ...        ...        ...   
256     recurrence-events  40-49    premeno           ?          ?         no   
257     recurrence-events  40-49    premeno           ?          ?          ?   
258     recurrence-events      ?          ?       30-34        6-8        yes   
259     recurrence-events  50-59       ge40       30-34        3-5         no   
260     recurrence-events  60-69       ge40           ?        3-5         no   
261     recurrence-events      ?       ge40       25-29      12-14          ?   
262                     ?      ?       ge40           ?        0-2         no   
263     recurrence-events  50-59       lt40       20-24        0-2          ?   
264     recurrence-events  50-59       lt40           ?        0-2          ?   
265     recurrence-events  30-39          ?       35-39          ?        yes   
266     recurrence-events  40-49    premeno       30-34        3-5          ?   
267     recurrence-events  60-69          ?       20-24      24-26        yes   
268                     ?  30-39    premeno       35-39        0-2          ?   
269                     ?  40-49    premeno       25-29        0-2         no   
270                     ?  50-59       ge40       30-34        6-8        yes   
271     recurrence-events      ?    premeno           ?        0-2         no   
272     recurrence-events  40-49          ?       15-19        0-2        yes   
273                     ?  60-69       ge40        

In [10]:
#One-Hot encoding on the dataset with '?'

In [11]:
encodedDF = pd.get_dummies(newBreast)
encodedDF

class_?  class_no-recurrence-events  class_recurrence-events   age_20-29  \
0          1                           0                        0           0   
1          0                           1                        0           0   
2          0                           1                        0           0   
3          1                           0                        0           0   
4          0                           1                        0           0   
5          0                           1                        0           0   
6          1                           0                        0           0   
7          0                           1                        0           0   
8          1                           0                        0           0   
9          0                           1                        0           0   
10         1                           0                        0           0   
11         0                           1                        0           0   
12         0                           1                        0           0   
13         0                           1                        0           0   
14         0                           1                        0           0   
15         0                           1                        0           0   
16         1                           0                        0           0   
17         0                           1                        0           0   
18         0                           1                        0           0   
19         1                           0                        0           0   
20         0                           1                        0           0   
21         0                           1                        0           0   
22         0                           1                        0           0   
23         0                           1                        0           0   
24         0                           1                        0           0   
25         0                           1                        0           0   
26         0                           1                        0           0   
27         0                           1                        0           0   
28         1                           0                        0           0   
29         0                           1                        0           0   
..       ...                         ...                      ...         ...   
256        0                           0                        1           0   
257        0                           0                        1           0   
258        0                           0                        1           0   
259        0                           0                        1           0   
260        0                           0                        1           0   
261        0                           0                        1           0   
262        1                           0                        0           0   
263        0                           0                        1           0   
264        0                           0                        1           0   
265        0                           0                        1           0   
266        0                           0                        1           0   
267        0                           0                        1           0   
268        1                           0                        0           0   
269        1                           0                        0           0   
270        1                           0                        0           0   
271        0                           0                        1           0   
272        0                           0                        1           0   
273        1                        

In [12]:
#Divide input & output in with the latter is equal to labels

In [13]:
def preprocessing(dataframe, dataframeLabels):
    y = dataframeLabels.values
    x = dataframe.drop(dataframeLabels.columns, axis=1).values
    
    return x,y

In [14]:
#Split the TrainSet e TestSet, if there is a '?' it is in the TestSet else in the TrainSet

In [15]:
def split_train_test(x, y, y_original, index):
    x_train = []
    x_test = []
    y_train = []
    y_test = []
    y_test_original = []
    
    for i in range (0, len(y)):
        for j in index:
            if y[i][j] == 1:
                y_test.append(y[i].tolist())
                y_test_original.append(y_original[i].tolist())
                x_test.append(x[i].tolist())

            else:
                y_train.append(y[i].tolist())
                x_train.append(x[i].tolist())
    
    return array(x_train), array(x_test), array(y_train), array(y_test), array(y_test_original)

In [16]:
#Create the Neural Network

In [17]:
def NN(x_train, y_train, hidden, iterations):
    classifier = MLPClassifier(hidden_layer_sizes=hidden,max_iter=iterations)
    classifier.fit(x_train, y_train) 
    
    return classifier

In [18]:
#Create every possible subset, for creating a Neural Network for every of it

In [19]:
def possible_subsets(df, max_output):
    possible_subsets = []
    for i in range (1, max_output):
        for subset in itertools.combinations(df.columns, i):
            possible_subsets.append(list(subset))
    
    return possible_subsets

In [20]:
#Labels is equal to a set of output columns of oneHotEncoding are under consideration

In [21]:
def createLabels(subset, one_hot_labels):
    labels = []
    
    for label in subset:
        for one_hot_label in one_hot_labels:
            if label in one_hot_label:
                labels.append(one_hot_label)
    
    return labels

In [22]:
#Unknown is equal to the list of columns with '?' in oneHotEncoding

In [23]:
def createUnknownLabels(labels, unknown):
    for label in labels:
        if '?' in label:
            unknown.append(label)
    
    return unknown

In [24]:
#Train and predict probabilistic vector

In [25]:
def trainAndPredictProba(classifier, x_test_breast):
    y_pred_breast_prob = classifier.predict_proba(x_test_breast)
    y_pred_breast = classifier.predict(x_test_breast)
    
    return y_pred_breast_prob

In [26]:
#Common training and prediction

In [27]:
def trainAndPredict(classifier, x_test_breast):
    y_pred_breast_prob = classifier.predict_proba(x_test_breast)
    y_pred_breast = classifier.predict(x_test_breast)
    
    return y_pred_breast

In [28]:
def correctlyReindex(index, y_pred_breast):
    flag = False
    for i in index:
        if flag:
            i = i-1
        y_pred_breast = np.delete(y_pred_breast, i, axis=1)
        flag = True
            
    return y_pred_breast

In [29]:
def printZeroOneLoss(y_test_brest_original, y_pred_breast):
    Loss = zero_one_loss(y_test_brest_original, y_pred_breast)
    
    print("0/1 Loss:")
    print(Loss)
    print("-------------------------------------------")

In [30]:
def printProbabilisticLoss(y_test_brest_original, y_pred_breast):
    Loss = log_loss(y_test_brest_original, y_pred_breast)
    
    print("Log Loss:")
    print(Loss)
    print("-------------------------------------------")

In [31]:
def printCase(subset):
    
    print("Case: {subset} with ?".format(subset=subset))
    print("-------------------------------------------")

In [32]:
def printTrainTest(x_train, x_test):
    
    print("Train-Test sizes:")    
    print("{train}% train".format(train=int(round(100*len(x_train)/(len(x_train)+len(x_test))))))
    print("{test}% test".format(test=int(round(100*len(x_test)/(len(x_train)+len(x_test))))))
    print("-------------------------------------------")

In [33]:
def printLabels(labels):
    
    print("Possible values to predict:")
    print(labels)
    print("--------------------------------------------")

In [34]:
def printProbabilityVector(y_pred_breast_prob):

    print('Prediction probability for each entry in test:')
    print(y_pred_breast_prob)
    print("--------------------------------------------")

In [35]:
def printQuestionMarks(newBreast):
    
    for i in range(0, len(newBreast)):
        for j in range(0, len(newBreast.columns) -1):
            if '?' in j:
                print('here')
            
    print('Question marks percentage:')
    
    print("--------------------------------------------")

In [36]:
def printEverything(subset, x_train_breast, x_test_breast, labels, y_pred_breast_prob, y_test_brest_original, y_pred_breast, newBreast):
    
    printCase(subset)
    printTrainTest(x_train_breast, x_test_breast)
    printLabels(labels)
    printProbabilityVector(y_pred_breast_prob)
    printZeroOneLoss(y_test_brest_original, y_pred_breast)
    printProbabilisticLoss(y_test_brest_original, y_pred_breast)
    #printQuestionMarks(newBreast)

In [37]:
#unknown = lista di colonne con il '?' di oneHotEncoding
#index = indici colonne di unknown
#labels = insieme delle colonne di output che stiamo considerando di oneHotEncoding
#one_hot_labels = colonne del df codificato ('encodedDF')

In [38]:
def probPredict():
    #For every subset of possible columns as output
    for subset in possible_subsets(breast, 3):
        labels = [] 
        unknown = [] 
        one_hot_labels = encodedDF.columns 
        
        labels = createLabels(subset, one_hot_labels)
        labels_original = [x for x in labels if "?" not in x ]

        #Divide input and output where outputs are equal to output columns in encodedDF
        x_breast, y_breast = preprocessing(encodedDF, encodedDF[labels])
        
        #Equal, but for the original dataset
        x_breast_original, y_breast_original = preprocessing(breast_df_original_one_hot, breast_df_original_one_hot[labels_original])
            
        #Create unknown list
        unknown = createUnknownLabels(labels, unknown)
        
        #create index
        index = [labels.index(x) for x in unknown] # indici colonne con ? con one_hot_encoding
        
        #Split train and test where test is equal yo rows containing '?' in output rows
        x_train_breast, x_test_breast, y_train_breast, y_test_breast, y_test_brest_original = split_train_test(x_breast, y_breast, y_breast_original, index)     
        
        #Train e predict using Neural Nets
        m = int(len(breast.columns)+len(labels)/2)
        classifier = NN(x_train_breast, y_train_breast, (m*3,m*2), 5000)
        
        y_pred_breast_prob = trainAndPredictProba(classifier, x_test_breast)
        y_pred_breast = trainAndPredict(classifier, x_test_breast)
        
        #Perform the reindex since deleting the considered column it changes
        y_pred_breast = correctlyReindex(index, y_pred_breast)
        
        printEverything(subset, x_train_breast, x_test_breast, labels, y_pred_breast_prob, y_test_brest_original, y_pred_breast, newBreast)
        print( )
        print( )
        print( )

# Fare

In [39]:
#percentuale punti interrogativi = # punti interrogativi / numero di righe per numero di colonne

In [40]:
probPredict()

Case: ['class'] with ?
-------------------------------------------
Train-Test sizes:
71% train
29% test
-------------------------------------------
Possible values to predict:
['class_?', 'class_no-recurrence-events', 'class_recurrence-events']
--------------------------------------------
Prediction probability for each entry in test:
[[2.35832846e-03 6.53827550e-01 3.63445856e-01]
 [7.60713948e-04 8.89202711e-01 1.17068923e-01]
 [2.18076540e-03 8.23802915e-01 2.09146851e-01]
 [3.78557438e-03 7.35387560e-01 2.47402254e-01]
 [1.52445660e-03 8.35879743e-01 1.69294021e-01]
 [3.11220974e-03 8.29573693e-01 1.62278560e-01]
 [4.10562871e-03 7.18773790e-01 3.40156015e-01]
 [3.19786505e-03 5.87285109e-01 4.45442227e-01]
 [1.22400181e-03 8.86115160e-01 1.27768572e-01]
 [5.81036839e-03 7.57540970e-01 2.46030617e-01]
 [3.35822298e-03 8.86868080e-01 1.51613145e-01]
 [3.90080145e-03 7.73854537e-01 2.44919023e-01]
 [1.21530933e-03 8.44967575e-01 1.76329482e-01]
 [4.72107622e-04 9.39922235e-01 7.52515

Case: [' menopause'] with ?
-------------------------------------------
Train-Test sizes:
75% train
25% test
-------------------------------------------
Possible values to predict:
[' menopause_?', ' menopause_ge40', ' menopause_lt40', ' menopause_premeno']
--------------------------------------------
Prediction probability for each entry in test:
[[1.11476389e-03 8.69054155e-02 1.33267940e-02 9.22820824e-01]
 [2.17585803e-03 8.51214386e-01 1.68790785e-02 9.58272070e-02]
 [8.81365026e-03 5.57463908e-01 5.53483674e-02 3.97427975e-01]
 [3.50240367e-03 6.92615018e-01 1.37522566e-01 1.79869017e-01]
 [5.34364888e-04 4.93480643e-02 8.93585929e-03 9.59019401e-01]
 [8.43187790e-03 8.92943539e-01 7.57327525e-02 1.03291322e-01]
 [1.57937555e-03 6.42193671e-01 3.67107342e-02 3.70151742e-01]
 [2.40277758e-03 7.85194621e-01 2.27073552e-02 2.57220771e-01]
 [1.33843643e-03 1.24199894e-01 2.46281616e-02 8.66889337e-01]
 [8.83191120e-04 1.90606477e-01 1.84265675e-02 8.68050534e-01]
 [4.48404807e-04 6.7

Case: [' node-caps'] with ?
-------------------------------------------
Train-Test sizes:
74% train
26% test
-------------------------------------------
Possible values to predict:
[' node-caps_?', ' node-caps_no', ' node-caps_yes']
--------------------------------------------
Prediction probability for each entry in test:
[[2.66486728e-04 9.80736986e-01 2.33455070e-02]
 [2.75111409e-04 9.72282176e-01 2.43142765e-02]
 [4.16549805e-04 9.75473586e-01 1.55066858e-02]
 [2.83270754e-04 9.96756469e-01 2.48722883e-03]
 [5.27992598e-04 8.75034710e-01 1.34152777e-01]
 [7.10436797e-04 9.70582931e-01 2.97523421e-02]
 [3.22374870e-04 5.80645758e-01 3.96370930e-01]
 [1.93514062e-04 9.58460176e-01 4.87380695e-02]
 [2.96967585e-04 9.97922565e-01 1.52324351e-03]
 [4.76701443e-04 9.78317514e-01 2.04665017e-02]
 [2.87251352e-04 9.82337241e-01 1.70964658e-02]
 [1.84638427e-04 9.88062852e-01 1.12267612e-02]
 [1.70344470e-03 9.72815041e-01 1.54713710e-02]
 [1.83382472e-03 9.82817385e-01 1.06485665e-02]
 [5

Case: [' breast'] with ?
-------------------------------------------
Train-Test sizes:
71% train
29% test
-------------------------------------------
Possible values to predict:
[' breast_?', ' breast_left', ' breast_right', ' breast-quad_?', ' breast-quad_central', ' breast-quad_left_low', ' breast-quad_left_up', ' breast-quad_right_low', ' breast-quad_right_up']
--------------------------------------------
Prediction probability for each entry in test:
[[0.25314988 0.42716721 0.3404374  ... 0.23287783 0.08805841 0.08619262]
 [0.18648631 0.33017232 0.52151384 ... 0.42473329 0.02622284 0.09303828]
 [0.19523276 0.10868993 0.68032709 ... 0.1467122  0.01510696 0.16879532]
 ...
 [0.1620898  0.71180284 0.15685759 ... 0.10476608 0.0415997  0.04505057]
 [0.17843848 0.48227966 0.3729353  ... 0.15666392 0.12552446 0.08883589]
 [0.17843848 0.48227966 0.3729353  ... 0.15666392 0.12552446 0.08883589]]
--------------------------------------------
0/1 Loss:
0.9520958083832335
-----------------------

Case: ['class', ' age'] with ?
-------------------------------------------
Train-Test sizes:
72% train
28% test
-------------------------------------------
Possible values to predict:
['class_?', 'class_no-recurrence-events', 'class_recurrence-events', ' age_20-29', ' age_30-39', ' age_40-49', ' age_50-59', ' age_60-69', ' age_70-79', ' age_?']
--------------------------------------------
Prediction probability for each entry in test:
[[0.22990066 0.48854538 0.10814935 ... 0.00122567 0.01180811 0.23680785]
 [0.75722864 0.2370483  0.03018742 ... 0.48498493 0.01420381 0.27406429]
 [0.75722864 0.2370483  0.03018742 ... 0.48498493 0.01420381 0.27406429]
 ...
 [0.19527818 0.54320945 0.09977121 ... 0.440671   0.04358753 0.1544269 ]
 [0.12201747 0.26268653 0.47329879 ... 0.30824252 0.00894264 0.25243712]
 [0.25600779 0.08751684 0.6709972  ... 0.06257706 0.00939214 0.60341086]]
--------------------------------------------
0/1 Loss:
0.930379746835443
-------------------------------------------


Case: ['class', ' deg-malig'] with ?
-------------------------------------------
Train-Test sizes:
73% train
27% test
-------------------------------------------
Possible values to predict:
['class_?', 'class_no-recurrence-events', 'class_recurrence-events', ' deg-malig_1', ' deg-malig_2', ' deg-malig_3', ' deg-malig_?']
--------------------------------------------
Prediction probability for each entry in test:
[[0.62428482 0.07293835 0.16634148 ... 0.11098052 0.25829261 0.0694289 ]
 [0.7807179  0.08051314 0.0886369  ... 0.77953411 0.03789159 0.02899961]
 [0.47589259 0.15443105 0.17381397 ... 0.15198279 0.05318034 0.80013218]
 ...
 [0.1884612  0.35083509 0.25429313 ... 0.07014155 0.21574648 0.78485458]
 [0.1884612  0.35083509 0.25429313 ... 0.07014155 0.21574648 0.78485458]
 [0.23115941 0.47684025 0.16984151 ... 0.28834374 0.10315236 0.61501861]]
--------------------------------------------
0/1 Loss:
0.9675324675324676
-------------------------------------------
Log Loss:
30.8870107072

Case: [' age', ' menopause'] with ?
-------------------------------------------
Train-Test sizes:
74% train
26% test
-------------------------------------------
Possible values to predict:
[' age_20-29', ' age_30-39', ' age_40-49', ' age_50-59', ' age_60-69', ' age_70-79', ' age_?', ' menopause_?', ' menopause_ge40', ' menopause_lt40', ' menopause_premeno']
--------------------------------------------
Prediction probability for each entry in test:
[[2.30212909e-05 1.62038551e-02 2.14903659e-01 ... 9.92478933e-02
  1.05244452e-02 5.49699454e-02]
 [4.54851355e-05 2.37162421e-03 5.31505228e-03 ... 9.37789146e-01
  2.30867668e-04 1.30834739e-03]
 [1.89048937e-07 9.71846920e-04 3.59866957e-02 ... 5.63935940e-01
  5.91090478e-05 6.18813755e-03]
 ...
 [1.34329818e-06 2.10771299e-02 4.23827359e-02 ... 5.42775333e-04
  1.74898085e-05 7.96086574e-01]
 [9.27901184e-07 5.35264305e-01 1.22910081e-04 ... 1.30627636e-01
  9.27057043e-06 4.48709590e-02]
 [4.21741403e-10 1.94249213e-04 2.54607424e-04 .

Case: [' age', ' irradiat'] with ?
-------------------------------------------
Train-Test sizes:
74% train
26% test
-------------------------------------------
Possible values to predict:
[' age_20-29', ' age_30-39', ' age_40-49', ' age_50-59', ' age_60-69', ' age_70-79', ' age_?', ' irradiat_?', ' irradiat_no', ' irradiat_yes']
--------------------------------------------
Prediction probability for each entry in test:
[[2.07132972e-03 3.04501020e-06 1.24468315e-02 ... 1.89947118e-02
  8.65688140e-01 1.19384857e-02]
 [5.72956823e-03 1.39440025e-02 8.60229793e-01 ... 8.27630186e-01
  1.36905799e-01 2.43602940e-02]
 [1.31690096e-03 2.07901586e-03 3.18583166e-03 ... 8.18243160e-01
  1.46329561e-02 1.73522658e-01]
 ...
 [1.32061300e-03 9.25210028e-01 8.30428803e-02 ... 6.25740285e-01
  1.30434187e-01 9.30635223e-02]
 [1.20380524e-04 2.86006058e-03 1.41873810e-01 ... 6.10376301e-01
  3.80675379e-01 3.15229266e-03]
 [7.62183133e-05 7.18783196e-02 3.69810789e-04 ... 9.61230904e-02
  8.0039052

Case: [' menopause', ' irradiat'] with ?
-------------------------------------------
Train-Test sizes:
75% train
25% test
-------------------------------------------
Possible values to predict:
[' menopause_?', ' menopause_ge40', ' menopause_lt40', ' menopause_premeno', ' irradiat_?', ' irradiat_no', ' irradiat_yes']
--------------------------------------------
Prediction probability for each entry in test:
[[8.92731940e-01 4.08060630e-04 3.27337468e-02 ... 6.85204433e-03
  9.35253815e-01 2.47262655e-02]
 [9.64439759e-02 9.17505210e-04 1.02887804e-02 ... 9.57038972e-01
  7.15712963e-02 1.15981361e-02]
 [1.46987498e-01 9.66630290e-01 6.95508329e-02 ... 8.70753493e-01
  1.62869501e-01 3.22104309e-02]
 ...
 [1.86157063e-03 1.63537741e-03 7.40833037e-04 ... 7.79634032e-01
  2.58271334e-02 6.75720140e-02]
 [7.79590873e-01 7.97897402e-02 2.02119646e-03 ... 1.12894557e-03
  1.85104995e-01 9.00806233e-01]
 [3.16246582e-03 9.26803566e-01 3.57760796e-04 ... 7.68551668e-01
  9.45822035e-02 4.8356

Case: [' inv-nodes', ' node-caps'] with ?
-------------------------------------------
Train-Test sizes:
74% train
26% test
-------------------------------------------
Possible values to predict:
[' inv-nodes_0-2', ' inv-nodes_12-14', ' inv-nodes_15-17', ' inv-nodes_24-26', ' inv-nodes_3-5', ' inv-nodes_6-8', ' inv-nodes_9-11', ' inv-nodes_?', ' node-caps_?', ' node-caps_no', ' node-caps_yes']
--------------------------------------------
Prediction probability for each entry in test:
[[2.15635142e-02 6.86677087e-05 8.08504475e-04 ... 3.54497095e-01
  4.87448310e-01 3.23507371e-03]
 [2.15635142e-02 6.86677087e-05 8.08504475e-04 ... 3.54497095e-01
  4.87448310e-01 3.23507371e-03]
 [9.61350655e-01 1.13801336e-06 2.64421006e-03 ... 8.69196895e-01
  1.70134871e-02 3.65164982e-02]
 ...
 [9.91974473e-01 1.12090698e-04 1.42058094e-04 ... 7.96951672e-01
  7.94690971e-03 4.18454130e-02]
 [1.12984270e-02 3.41239811e-04 3.55689268e-04 ... 2.04103613e-01
  4.05974116e-04 9.88768881e-01]
 [3.86351491

Case: [' node-caps', ' breast-quad'] with ?
-------------------------------------------
Train-Test sizes:
73% train
27% test
-------------------------------------------
Possible values to predict:
[' node-caps_?', ' node-caps_no', ' node-caps_yes', ' breast-quad_?', ' breast-quad_central', ' breast-quad_left_low', ' breast-quad_left_up', ' breast-quad_right_low', ' breast-quad_right_up']
--------------------------------------------
Prediction probability for each entry in test:
[[8.66546185e-01 3.73285182e-02 7.79220777e-04 ... 2.83212651e-04
  4.99176922e-01 4.51850471e-04]
 [2.13528581e-02 8.64298085e-01 5.18558930e-03 ... 1.93450588e-03
  8.48586303e-05 9.97259636e-02]
 [7.78320046e-01 6.45087588e-03 1.15893255e-01 ... 1.82743776e-04
  7.68027688e-01 6.49537364e-05]
 ...
 [1.31883137e-01 3.23700057e-03 9.31613177e-01 ... 4.33188409e-02
  2.40409239e-05 1.93445356e-02]
 [2.27848228e-02 4.41780337e-03 8.83529590e-01 ... 3.00388664e-06
  3.99736226e-03 4.35181239e-03]
 [2.60370067e-02 

Case: [' deg-malig', ' breast'] with ?
-------------------------------------------
Train-Test sizes:
72% train
28% test
-------------------------------------------
Possible values to predict:
[' deg-malig_1', ' deg-malig_2', ' deg-malig_3', ' deg-malig_?', ' breast_?', ' breast_left', ' breast_right', ' breast-quad_?', ' breast-quad_central', ' breast-quad_left_low', ' breast-quad_left_up', ' breast-quad_right_low', ' breast-quad_right_up']
--------------------------------------------
Prediction probability for each entry in test:
[[4.85326127e-01 1.50071399e-01 1.83339687e-01 ... 2.94546719e-01
  1.42379658e-02 1.60817413e-03]
 [3.29905940e-01 2.04311949e-01 9.02008592e-02 ... 1.25134905e-02
  7.51324032e-04 5.79235820e-02]
 [3.18423551e-02 8.74682005e-01 2.46343823e-02 ... 1.31590644e-02
  1.14602666e-03 9.75111168e-02]
 ...
 [2.26467555e-02 9.21651178e-02 3.21737513e-01 ... 2.37470486e-01
  3.00206047e-04 3.16845415e-03]
 [1.11196844e-02 9.50767466e-03 1.81068241e-01 ... 7.61381450e